# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'igs_gui.ui'
#
# Created: Mon Aug 01 20:50:21 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1750, 983)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.viewArenaXY = QtGui.QGraphicsView(self.centralwidget)
        self.viewArenaXY.setGeometry(QtCore.QRect(250, 10, 1150, 650))
        self.viewArenaXY.setProperty("cursor", QtCore.Qt.CrossCursor)
        self.viewArenaXY.setMouseTracking(True)
        self.viewArenaXY.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewArenaXY.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewArenaXY.setObjectName("viewArenaXY")
        self.viewArenaXZ = QtGui.QGraphicsView(self.centralwidget)
        self.viewArenaXZ.setGeometry(QtCore.QRect(250, 670, 1151, 291))
        self.viewArenaXZ.setProperty("cursor", QtCore.Qt.CrossCursor)
        self.viewArenaXZ.setMouseTracking(True)
        self.viewArenaXZ.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewArenaXZ.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewArenaXZ.setObjectName("viewArenaXZ")
        self.groupMarkedLocations = QtGui.QGroupBox(self.centralwidget)
        self.groupMarkedLocations.setGeometry(QtCore.QRect(10, 630, 231, 331))
        self.groupMarkedLocations.setObjectName("groupMarkedLocations")
        self.pbtnADDWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnADDWP.setGeometry(QtCore.QRect(10, 170, 101, 21))
        self.pbtnADDWP.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnADDWP.setObjectName("pbtnADDWP")
        self.pbtnREMOVEWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnREMOVEWP.setGeometry(QtCore.QRect(10, 200, 101, 21))
        self.pbtnREMOVEWP.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnREMOVEWP.setObjectName("pbtnREMOVEWP")
        self.pbtnGOTO = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnGOTO.setGeometry(QtCore.QRect(10, 230, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbtnGOTO.setFont(font)
        self.pbtnGOTO.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnGOTO.setObjectName("pbtnGOTO")
        self.layoutWidget = QtGui.QWidget(self.groupMarkedLocations)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 280, 211, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setSpacing(3)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.labelZ_L = QtGui.QLabel(self.layoutWidget)
        self.labelZ_L.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_L.setObjectName("labelZ_L")
        self.gridLayout_8.addWidget(self.labelZ_L, 0, 2, 1, 1)
        self.labelX_L = QtGui.QLabel(self.layoutWidget)
        self.labelX_L.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_L.setObjectName("labelX_L")
        self.gridLayout_8.addWidget(self.labelX_L, 0, 0, 1, 1)
        self.savedLocZ = QtGui.QLineEdit(self.layoutWidget)
        self.savedLocZ.setObjectName("savedLocZ")
        self.gridLayout_8.addWidget(self.savedLocZ, 2, 2, 1, 1)
        self.savedLocY = QtGui.QLineEdit(self.layoutWidget)
        self.savedLocY.setObjectName("savedLocY")
        self.gridLayout_8.addWidget(self.savedLocY, 2, 1, 1, 1)
        self.savedLocX = QtGui.QLineEdit(self.layoutWidget)
        self.savedLocX.setObjectName("savedLocX")
        self.gridLayout_8.addWidget(self.savedLocX, 2, 0, 1, 1)
        self.labelH_L = QtGui.QLabel(self.layoutWidget)
        self.labelH_L.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_L.setObjectName("labelH_L")
        self.gridLayout_8.addWidget(self.labelH_L, 0, 3, 1, 1)
        self.savedLocH = QtGui.QLineEdit(self.layoutWidget)
        self.savedLocH.setObjectName("savedLocH")
        self.gridLayout_8.addWidget(self.savedLocH, 2, 3, 1, 1)
        self.labelY_L = QtGui.QLabel(self.layoutWidget)
        self.labelY_L.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_L.setObjectName("labelY_L")
        self.gridLayout_8.addWidget(self.labelY_L, 0, 1, 1, 1)
        self.markedLocationsList = QtGui.QListWidget(self.groupMarkedLocations)
        self.markedLocationsList.setGeometry(QtCore.QRect(120, 20, 101, 251))
        self.markedLocationsList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.markedLocationsList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.markedLocationsList.setObjectName("markedLocationsList")
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        QtGui.QListWidgetItem(self.markedLocationsList)
        self.pbtnETCWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnETCWP.setGeometry(QtCore.QRect(10, 140, 101, 23))
        self.pbtnETCWP.setObjectName("pbtnETCWP")
        self.pbtnDROPWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnDROPWP.setGeometry(QtCore.QRect(10, 50, 101, 23))
        self.pbtnDROPWP.setObjectName("pbtnDROPWP")
        self.pbtnSHOOTWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnSHOOTWP.setGeometry(QtCore.QRect(10, 80, 101, 23))
        self.pbtnSHOOTWP.setObjectName("pbtnSHOOTWP")
        self.pbtnBLOCKWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnBLOCKWP.setGeometry(QtCore.QRect(10, 110, 101, 23))
        self.pbtnBLOCKWP.setObjectName("pbtnBLOCKWP")
        self.pbtnALLWP = QtGui.QPushButton(self.groupMarkedLocations)
        self.pbtnALLWP.setGeometry(QtCore.QRect(10, 20, 101, 23))
        self.pbtnALLWP.setObjectName("pbtnALLWP")
        self.groupCopterActions = QtGui.QGroupBox(self.centralwidget)
        self.groupCopterActions.setGeometry(QtCore.QRect(1410, 600, 331, 361))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupCopterActions.setFont(font)
        self.groupCopterActions.setObjectName("groupCopterActions")
        self.pbtnARM = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnARM.setGeometry(QtCore.QRect(20, 30, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnARM.setFont(font)
        self.pbtnARM.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnARM.setObjectName("pbtnARM")
        self.pbtnLAND = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnLAND.setGeometry(QtCore.QRect(170, 30, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnLAND.setFont(font)
        self.pbtnLAND.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnLAND.setObjectName("pbtnLAND")
        self.pbtnDISCONNECT = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnDISCONNECT.setGeometry(QtCore.QRect(170, 270, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbtnDISCONNECT.setFont(font)
        self.pbtnDISCONNECT.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnDISCONNECT.setObjectName("pbtnDISCONNECT")
        self.pbtnKILL_CONFIRM = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnKILL_CONFIRM.setGeometry(QtCore.QRect(130, 270, 31, 51))
        self.pbtnKILL_CONFIRM.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnKILL_CONFIRM.setText("")
        self.pbtnKILL_CONFIRM.setCheckable(False)
        self.pbtnKILL_CONFIRM.setObjectName("pbtnKILL_CONFIRM")
        self.pbtnKILL = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnKILL.setGeometry(QtCore.QRect(20, 270, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbtnKILL.setFont(font)
        self.pbtnKILL.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnKILL.setCheckable(False)
        self.pbtnKILL.setObjectName("pbtnKILL")
        self.copterSpeed = QtGui.QDoubleSpinBox(self.groupCopterActions)
        self.copterSpeed.setGeometry(QtCore.QRect(90, 330, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copterSpeed.setFont(font)
        self.copterSpeed.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.copterSpeed.setDecimals(1)
        self.copterSpeed.setMinimum(0.1)
        self.copterSpeed.setMaximum(5.0)
        self.copterSpeed.setSingleStep(0.1)
        self.copterSpeed.setProperty("value", 0.1)
        self.copterSpeed.setObjectName("copterSpeed")
        self.labelMaxSpeed = QtGui.QLabel(self.groupCopterActions)
        self.labelMaxSpeed.setGeometry(QtCore.QRect(10, 330, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxSpeed.setFont(font)
        self.labelMaxSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaxSpeed.setObjectName("labelMaxSpeed")
        self.labelMaxSpeed_2 = QtGui.QLabel(self.groupCopterActions)
        self.labelMaxSpeed_2.setGeometry(QtCore.QRect(140, 330, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxSpeed_2.setFont(font)
        self.labelMaxSpeed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaxSpeed_2.setObjectName("labelMaxSpeed_2")
        self.pbtnDISCONNECT_CONFIRM = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnDISCONNECT_CONFIRM.setGeometry(QtCore.QRect(280, 270, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnDISCONNECT_CONFIRM.setFont(font)
        self.pbtnDISCONNECT_CONFIRM.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnDISCONNECT_CONFIRM.setText("")
        self.pbtnDISCONNECT_CONFIRM.setObjectName("pbtnDISCONNECT_CONFIRM")
        self.labelIncrementSpeed = QtGui.QLabel(self.groupCopterActions)
        self.labelIncrementSpeed.setGeometry(QtCore.QRect(180, 330, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelIncrementSpeed.setFont(font)
        self.labelIncrementSpeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelIncrementSpeed.setObjectName("labelIncrementSpeed")
        self.labelIncrementSpeedVALUE = QtGui.QLabel(self.groupCopterActions)
        self.labelIncrementSpeedVALUE.setGeometry(QtCore.QRect(280, 330, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelIncrementSpeedVALUE.setFont(font)
        self.labelIncrementSpeedVALUE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelIncrementSpeedVALUE.setObjectName("labelIncrementSpeedVALUE")
        self.pbtnFLIP = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnFLIP.setGeometry(QtCore.QRect(20, 90, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.pbtnFLIP.setFont(font)
        self.pbtnFLIP.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnFLIP.setObjectName("pbtnFLIP")
        self.pbtnLOB = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnLOB.setGeometry(QtCore.QRect(170, 90, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.pbtnLOB.setFont(font)
        self.pbtnLOB.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnLOB.setObjectName("pbtnLOB")
        self.pbtnFOLLOW = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnFOLLOW.setGeometry(QtCore.QRect(20, 150, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnFOLLOW.setFont(font)
        self.pbtnFOLLOW.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnFOLLOW.setObjectName("pbtnFOLLOW")
        self.pbtnPLATOON = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnPLATOON.setGeometry(QtCore.QRect(170, 150, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnPLATOON.setFont(font)
        self.pbtnPLATOON.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnPLATOON.setObjectName("pbtnPLATOON")
        self.pbtnPATROL = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnPATROL.setGeometry(QtCore.QRect(20, 210, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnPATROL.setFont(font)
        self.pbtnPATROL.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnPATROL.setObjectName("pbtnPATROL")
        self.pbtnWALL = QtGui.QPushButton(self.groupCopterActions)
        self.pbtnWALL.setGeometry(QtCore.QRect(170, 210, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbtnWALL.setFont(font)
        self.pbtnWALL.setCursor(QtCore.Qt.PointingHandCursor)
        self.pbtnWALL.setObjectName("pbtnWALL")
        self.groupCopter_1 = QtGui.QGroupBox(self.centralwidget)
        self.groupCopter_1.setGeometry(QtCore.QRect(1410, 10, 331, 91))
        self.groupCopter_1.setTitle("")
        self.groupCopter_1.setObjectName("groupCopter_1")
        self.copterBatteryIndicator_1 = QtGui.QProgressBar(self.groupCopter_1)
        self.copterBatteryIndicator_1.setGeometry(QtCore.QRect(60, 10, 261, 16))
        self.copterBatteryIndicator_1.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.copterBatteryIndicator_1.setMinimum(130)
        self.copterBatteryIndicator_1.setMaximum(168)
        self.copterBatteryIndicator_1.setProperty("value", 129)
        self.copterBatteryIndicator_1.setTextVisible(False)
        self.copterBatteryIndicator_1.setOrientation(QtCore.Qt.Horizontal)
        self.copterBatteryIndicator_1.setObjectName("copterBatteryIndicator_1")
        self.layoutWidget_2 = QtGui.QWidget(self.groupCopter_1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 30, 211, 54))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.labelX_1 = QtGui.QLabel(self.layoutWidget_2)
        self.labelX_1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_1.setObjectName("labelX_1")
        self.gridLayout.addWidget(self.labelX_1, 0, 0, 1, 1)
        self.copterZ_1 = QtGui.QLabel(self.layoutWidget_2)
        self.copterZ_1.setAlignment(QtCore.Qt.AlignCenter)
        self.copterZ_1.setObjectName("copterZ_1")
        self.gridLayout.addWidget(self.copterZ_1, 1, 3, 1, 1)
        self.offsetZ_1 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.offsetZ_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetZ_1.setMinimum(-1.0)
        self.offsetZ_1.setMaximum(1.0)
        self.offsetZ_1.setSingleStep(0.01)
        self.offsetZ_1.setObjectName("offsetZ_1")
        self.gridLayout.addWidget(self.offsetZ_1, 2, 3, 1, 1)
        self.labelZ_1 = QtGui.QLabel(self.layoutWidget_2)
        self.labelZ_1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_1.setObjectName("labelZ_1")
        self.gridLayout.addWidget(self.labelZ_1, 0, 3, 1, 1)
        self.copterX_1 = QtGui.QLabel(self.layoutWidget_2)
        self.copterX_1.setAlignment(QtCore.Qt.AlignCenter)
        self.copterX_1.setObjectName("copterX_1")
        self.gridLayout.addWidget(self.copterX_1, 1, 0, 1, 1)
        self.offsetX_1 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.offsetX_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetX_1.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.offsetX_1.setMinimum(-1.0)
        self.offsetX_1.setMaximum(1.0)
        self.offsetX_1.setSingleStep(0.01)
        self.offsetX_1.setObjectName("offsetX_1")
        self.gridLayout.addWidget(self.offsetX_1, 2, 0, 1, 1)
        self.offsetY_1 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.offsetY_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetY_1.setMinimum(-1.0)
        self.offsetY_1.setMaximum(1.0)
        self.offsetY_1.setSingleStep(0.01)
        self.offsetY_1.setObjectName("offsetY_1")
        self.gridLayout.addWidget(self.offsetY_1, 2, 1, 1, 1)
        self.labelY_1 = QtGui.QLabel(self.layoutWidget_2)
        self.labelY_1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_1.setObjectName("labelY_1")
        self.gridLayout.addWidget(self.labelY_1, 0, 1, 1, 1)
        self.copterY_1 = QtGui.QLabel(self.layoutWidget_2)
        self.copterY_1.setAlignment(QtCore.Qt.AlignCenter)
        self.copterY_1.setObjectName("copterY_1")
        self.gridLayout.addWidget(self.copterY_1, 1, 1, 1, 1)
        self.labelH_1 = QtGui.QLabel(self.layoutWidget_2)
        self.labelH_1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_1.setObjectName("labelH_1")
        self.gridLayout.addWidget(self.labelH_1, 0, 4, 1, 1)
        self.copterH_1 = QtGui.QLabel(self.layoutWidget_2)
        self.copterH_1.setAlignment(QtCore.Qt.AlignCenter)
        self.copterH_1.setObjectName("copterH_1")
        self.gridLayout.addWidget(self.copterH_1, 1, 4, 1, 1)
        self.offsetH_1 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.offsetH_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetH_1.setDecimals(0)
        self.offsetH_1.setMinimum(-359.0)
        self.offsetH_1.setMaximum(359.0)
        self.offsetH_1.setSingleStep(1.0)
        self.offsetH_1.setObjectName("offsetH_1")
        self.gridLayout.addWidget(self.offsetH_1, 2, 4, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(self.groupCopter_1)
        self.layoutWidget_3.setGeometry(QtCore.QRect(60, 30, 51, 53))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.copterVolts_1 = QtGui.QLabel(self.layoutWidget_3)
        self.copterVolts_1.setObjectName("copterVolts_1")
        self.verticalLayout_3.addWidget(self.copterVolts_1)
        self.copterAmps_1 = QtGui.QLabel(self.layoutWidget_3)
        self.copterAmps_1.setObjectName("copterAmps_1")
        self.verticalLayout_3.addWidget(self.copterAmps_1)
        self.copterMode_1 = QtGui.QLabel(self.layoutWidget_3)
        self.copterMode_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copterMode_1.setObjectName("copterMode_1")
        self.verticalLayout_3.addWidget(self.copterMode_1)
        self.copterColor1 = QtGui.QPushButton(self.groupCopter_1)
        self.copterColor1.setGeometry(QtCore.QRect(10, 10, 41, 71))
        self.copterColor1.setCursor(QtCore.Qt.PointingHandCursor)
        self.copterColor1.setStyleSheet("font: bold italic 30pt \"Verdana\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.copterColor1.setObjectName("copterColor1")
        self.groupCopter_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupCopter_2.setGeometry(QtCore.QRect(1410, 110, 331, 91))
        self.groupCopter_2.setTitle("")
        self.groupCopter_2.setObjectName("groupCopter_2")
        self.copterBatteryIndicator_2 = QtGui.QProgressBar(self.groupCopter_2)
        self.copterBatteryIndicator_2.setGeometry(QtCore.QRect(60, 10, 261, 16))
        self.copterBatteryIndicator_2.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.copterBatteryIndicator_2.setMinimum(130)
        self.copterBatteryIndicator_2.setMaximum(168)
        self.copterBatteryIndicator_2.setProperty("value", 129)
        self.copterBatteryIndicator_2.setTextVisible(False)
        self.copterBatteryIndicator_2.setOrientation(QtCore.Qt.Horizontal)
        self.copterBatteryIndicator_2.setObjectName("copterBatteryIndicator_2")
        self.layoutWidget_4 = QtGui.QWidget(self.groupCopter_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(110, 30, 211, 54))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.copterY_2 = QtGui.QLabel(self.layoutWidget_4)
        self.copterY_2.setAlignment(QtCore.Qt.AlignCenter)
        self.copterY_2.setObjectName("copterY_2")
        self.gridLayout_2.addWidget(self.copterY_2, 1, 1, 1, 1)
        self.copterX_2 = QtGui.QLabel(self.layoutWidget_4)
        self.copterX_2.setAlignment(QtCore.Qt.AlignCenter)
        self.copterX_2.setObjectName("copterX_2")
        self.gridLayout_2.addWidget(self.copterX_2, 1, 0, 1, 1)
        self.offsetZ_2 = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.offsetZ_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetZ_2.setMinimum(-1.0)
        self.offsetZ_2.setMaximum(1.0)
        self.offsetZ_2.setSingleStep(0.01)
        self.offsetZ_2.setObjectName("offsetZ_2")
        self.gridLayout_2.addWidget(self.offsetZ_2, 2, 3, 1, 1)
        self.labelX_2 = QtGui.QLabel(self.layoutWidget_4)
        self.labelX_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_2.setObjectName("labelX_2")
        self.gridLayout_2.addWidget(self.labelX_2, 0, 0, 1, 1)
        self.copterZ_2 = QtGui.QLabel(self.layoutWidget_4)
        self.copterZ_2.setAlignment(QtCore.Qt.AlignCenter)
        self.copterZ_2.setObjectName("copterZ_2")
        self.gridLayout_2.addWidget(self.copterZ_2, 1, 3, 1, 1)
        self.labelY_2 = QtGui.QLabel(self.layoutWidget_4)
        self.labelY_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_2.setObjectName("labelY_2")
        self.gridLayout_2.addWidget(self.labelY_2, 0, 1, 1, 1)
        self.labelZ_2 = QtGui.QLabel(self.layoutWidget_4)
        self.labelZ_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_2.setObjectName("labelZ_2")
        self.gridLayout_2.addWidget(self.labelZ_2, 0, 3, 1, 1)
        self.offsetX_2 = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.offsetX_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetX_2.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.offsetX_2.setMinimum(-1.0)
        self.offsetX_2.setMaximum(1.0)
        self.offsetX_2.setSingleStep(0.01)
        self.offsetX_2.setObjectName("offsetX_2")
        self.gridLayout_2.addWidget(self.offsetX_2, 2, 0, 1, 1)
        self.offsetY_2 = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.offsetY_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetY_2.setMinimum(-1.0)
        self.offsetY_2.setMaximum(1.0)
        self.offsetY_2.setSingleStep(0.01)
        self.offsetY_2.setObjectName("offsetY_2")
        self.gridLayout_2.addWidget(self.offsetY_2, 2, 1, 1, 1)
        self.labelH_2 = QtGui.QLabel(self.layoutWidget_4)
        self.labelH_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_2.setObjectName("labelH_2")
        self.gridLayout_2.addWidget(self.labelH_2, 0, 4, 1, 1)
        self.copterH_2 = QtGui.QLabel(self.layoutWidget_4)
        self.copterH_2.setAlignment(QtCore.Qt.AlignCenter)
        self.copterH_2.setObjectName("copterH_2")
        self.gridLayout_2.addWidget(self.copterH_2, 1, 4, 1, 1)
        self.offsetH_2 = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.offsetH_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetH_2.setDecimals(0)
        self.offsetH_2.setMinimum(-359.0)
        self.offsetH_2.setMaximum(359.0)
        self.offsetH_2.setSingleStep(1.0)
        self.offsetH_2.setObjectName("offsetH_2")
        self.gridLayout_2.addWidget(self.offsetH_2, 2, 4, 1, 1)
        self.layoutWidget_5 = QtGui.QWidget(self.groupCopter_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(60, 30, 51, 53))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.copterVolts_2 = QtGui.QLabel(self.layoutWidget_5)
        self.copterVolts_2.setObjectName("copterVolts_2")
        self.verticalLayout_4.addWidget(self.copterVolts_2)
        self.copterAmps_2 = QtGui.QLabel(self.layoutWidget_5)
        self.copterAmps_2.setObjectName("copterAmps_2")
        self.verticalLayout_4.addWidget(self.copterAmps_2)
        self.copterMode_2 = QtGui.QLabel(self.layoutWidget_5)
        self.copterMode_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copterMode_2.setObjectName("copterMode_2")
        self.verticalLayout_4.addWidget(self.copterMode_2)
        self.copterColor2 = QtGui.QPushButton(self.groupCopter_2)
        self.copterColor2.setGeometry(QtCore.QRect(10, 10, 41, 71))
        self.copterColor2.setCursor(QtCore.Qt.PointingHandCursor)
        self.copterColor2.setStyleSheet("font: bold italic 30pt \"Verdana\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.copterColor2.setObjectName("copterColor2")
        self.groupCopter_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupCopter_4.setGeometry(QtCore.QRect(1410, 310, 331, 91))
        self.groupCopter_4.setTitle("")
        self.groupCopter_4.setObjectName("groupCopter_4")
        self.copterBatteryIndicator_4 = QtGui.QProgressBar(self.groupCopter_4)
        self.copterBatteryIndicator_4.setGeometry(QtCore.QRect(60, 10, 261, 16))
        self.copterBatteryIndicator_4.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.copterBatteryIndicator_4.setMinimum(130)
        self.copterBatteryIndicator_4.setMaximum(168)
        self.copterBatteryIndicator_4.setProperty("value", 129)
        self.copterBatteryIndicator_4.setTextVisible(False)
        self.copterBatteryIndicator_4.setOrientation(QtCore.Qt.Horizontal)
        self.copterBatteryIndicator_4.setObjectName("copterBatteryIndicator_4")
        self.layoutWidget_8 = QtGui.QWidget(self.groupCopter_4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(110, 30, 211, 54))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(1)
        self.gridLayout_4.setVerticalSpacing(3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.offsetY_4 = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.offsetY_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetY_4.setMinimum(-1.0)
        self.offsetY_4.setMaximum(1.0)
        self.offsetY_4.setSingleStep(0.01)
        self.offsetY_4.setObjectName("offsetY_4")
        self.gridLayout_4.addWidget(self.offsetY_4, 2, 1, 1, 1)
        self.offsetX_4 = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.offsetX_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetX_4.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.offsetX_4.setMinimum(-1.0)
        self.offsetX_4.setMaximum(1.0)
        self.offsetX_4.setSingleStep(0.01)
        self.offsetX_4.setObjectName("offsetX_4")
        self.gridLayout_4.addWidget(self.offsetX_4, 2, 0, 1, 1)
        self.copterX_4 = QtGui.QLabel(self.layoutWidget_8)
        self.copterX_4.setAlignment(QtCore.Qt.AlignCenter)
        self.copterX_4.setObjectName("copterX_4")
        self.gridLayout_4.addWidget(self.copterX_4, 1, 0, 1, 1)
        self.copterY_4 = QtGui.QLabel(self.layoutWidget_8)
        self.copterY_4.setAlignment(QtCore.Qt.AlignCenter)
        self.copterY_4.setObjectName("copterY_4")
        self.gridLayout_4.addWidget(self.copterY_4, 1, 1, 1, 1)
        self.offsetZ_4 = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.offsetZ_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetZ_4.setMinimum(-1.0)
        self.offsetZ_4.setMaximum(1.0)
        self.offsetZ_4.setSingleStep(0.01)
        self.offsetZ_4.setObjectName("offsetZ_4")
        self.gridLayout_4.addWidget(self.offsetZ_4, 2, 3, 1, 1)
        self.labelX_4 = QtGui.QLabel(self.layoutWidget_8)
        self.labelX_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_4.setObjectName("labelX_4")
        self.gridLayout_4.addWidget(self.labelX_4, 0, 0, 1, 1)
        self.copterZ_4 = QtGui.QLabel(self.layoutWidget_8)
        self.copterZ_4.setAlignment(QtCore.Qt.AlignCenter)
        self.copterZ_4.setObjectName("copterZ_4")
        self.gridLayout_4.addWidget(self.copterZ_4, 1, 3, 1, 1)
        self.labelY_4 = QtGui.QLabel(self.layoutWidget_8)
        self.labelY_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_4.setObjectName("labelY_4")
        self.gridLayout_4.addWidget(self.labelY_4, 0, 1, 1, 1)
        self.labelZ_4 = QtGui.QLabel(self.layoutWidget_8)
        self.labelZ_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_4.setObjectName("labelZ_4")
        self.gridLayout_4.addWidget(self.labelZ_4, 0, 3, 1, 1)
        self.labelH_4 = QtGui.QLabel(self.layoutWidget_8)
        self.labelH_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_4.setObjectName("labelH_4")
        self.gridLayout_4.addWidget(self.labelH_4, 0, 4, 1, 1)
        self.copterH_4 = QtGui.QLabel(self.layoutWidget_8)
        self.copterH_4.setAlignment(QtCore.Qt.AlignCenter)
        self.copterH_4.setObjectName("copterH_4")
        self.gridLayout_4.addWidget(self.copterH_4, 1, 4, 1, 1)
        self.offsetH_4 = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.offsetH_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetH_4.setDecimals(0)
        self.offsetH_4.setMinimum(-359.0)
        self.offsetH_4.setMaximum(359.0)
        self.offsetH_4.setSingleStep(1.0)
        self.offsetH_4.setObjectName("offsetH_4")
        self.gridLayout_4.addWidget(self.offsetH_4, 2, 4, 1, 1)
        self.layoutWidget_9 = QtGui.QWidget(self.groupCopter_4)
        self.layoutWidget_9.setGeometry(QtCore.QRect(60, 30, 51, 53))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.copterVolts_4 = QtGui.QLabel(self.layoutWidget_9)
        self.copterVolts_4.setObjectName("copterVolts_4")
        self.verticalLayout_6.addWidget(self.copterVolts_4)
        self.copterAmps_4 = QtGui.QLabel(self.layoutWidget_9)
        self.copterAmps_4.setObjectName("copterAmps_4")
        self.verticalLayout_6.addWidget(self.copterAmps_4)
        self.copterMode_4 = QtGui.QLabel(self.layoutWidget_9)
        self.copterMode_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copterMode_4.setObjectName("copterMode_4")
        self.verticalLayout_6.addWidget(self.copterMode_4)
        self.copterColor4 = QtGui.QPushButton(self.groupCopter_4)
        self.copterColor4.setGeometry(QtCore.QRect(10, 10, 41, 71))
        self.copterColor4.setCursor(QtCore.Qt.PointingHandCursor)
        self.copterColor4.setStyleSheet("font: bold italic 30pt \"Verdana\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.copterColor4.setObjectName("copterColor4")
        self.groupCopter_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupCopter_6.setGeometry(QtCore.QRect(1410, 510, 331, 91))
        self.groupCopter_6.setTitle("")
        self.groupCopter_6.setObjectName("groupCopter_6")
        self.copterBatteryIndicator_6 = QtGui.QProgressBar(self.groupCopter_6)
        self.copterBatteryIndicator_6.setGeometry(QtCore.QRect(60, 10, 261, 16))
        self.copterBatteryIndicator_6.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.copterBatteryIndicator_6.setMinimum(130)
        self.copterBatteryIndicator_6.setMaximum(168)
        self.copterBatteryIndicator_6.setProperty("value", 129)
        self.copterBatteryIndicator_6.setTextVisible(False)
        self.copterBatteryIndicator_6.setOrientation(QtCore.Qt.Horizontal)
        self.copterBatteryIndicator_6.setObjectName("copterBatteryIndicator_6")
        self.layoutWidget_12 = QtGui.QWidget(self.groupCopter_6)
        self.layoutWidget_12.setGeometry(QtCore.QRect(110, 30, 211, 54))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_12)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(1)
        self.gridLayout_6.setVerticalSpacing(3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.offsetY_6 = QtGui.QDoubleSpinBox(self.layoutWidget_12)
        self.offsetY_6.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetY_6.setMinimum(-1.0)
        self.offsetY_6.setMaximum(1.0)
        self.offsetY_6.setSingleStep(0.01)
        self.offsetY_6.setObjectName("offsetY_6")
        self.gridLayout_6.addWidget(self.offsetY_6, 2, 1, 1, 1)
        self.offsetX_6 = QtGui.QDoubleSpinBox(self.layoutWidget_12)
        self.offsetX_6.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetX_6.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.offsetX_6.setMinimum(-1.0)
        self.offsetX_6.setMaximum(1.0)
        self.offsetX_6.setSingleStep(0.01)
        self.offsetX_6.setObjectName("offsetX_6")
        self.gridLayout_6.addWidget(self.offsetX_6, 2, 0, 1, 1)
        self.copterX_6 = QtGui.QLabel(self.layoutWidget_12)
        self.copterX_6.setAlignment(QtCore.Qt.AlignCenter)
        self.copterX_6.setObjectName("copterX_6")
        self.gridLayout_6.addWidget(self.copterX_6, 1, 0, 1, 1)
        self.copterY_6 = QtGui.QLabel(self.layoutWidget_12)
        self.copterY_6.setAlignment(QtCore.Qt.AlignCenter)
        self.copterY_6.setObjectName("copterY_6")
        self.gridLayout_6.addWidget(self.copterY_6, 1, 1, 1, 1)
        self.offsetZ_6 = QtGui.QDoubleSpinBox(self.layoutWidget_12)
        self.offsetZ_6.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetZ_6.setMinimum(-1.0)
        self.offsetZ_6.setMaximum(1.0)
        self.offsetZ_6.setSingleStep(0.01)
        self.offsetZ_6.setObjectName("offsetZ_6")
        self.gridLayout_6.addWidget(self.offsetZ_6, 2, 3, 1, 1)
        self.labelX_6 = QtGui.QLabel(self.layoutWidget_12)
        self.labelX_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_6.setObjectName("labelX_6")
        self.gridLayout_6.addWidget(self.labelX_6, 0, 0, 1, 1)
        self.copterZ_6 = QtGui.QLabel(self.layoutWidget_12)
        self.copterZ_6.setAlignment(QtCore.Qt.AlignCenter)
        self.copterZ_6.setObjectName("copterZ_6")
        self.gridLayout_6.addWidget(self.copterZ_6, 1, 3, 1, 1)
        self.labelY_6 = QtGui.QLabel(self.layoutWidget_12)
        self.labelY_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_6.setObjectName("labelY_6")
        self.gridLayout_6.addWidget(self.labelY_6, 0, 1, 1, 1)
        self.labelZ_6 = QtGui.QLabel(self.layoutWidget_12)
        self.labelZ_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_6.setObjectName("labelZ_6")
        self.gridLayout_6.addWidget(self.labelZ_6, 0, 3, 1, 1)
        self.labelH_6 = QtGui.QLabel(self.layoutWidget_12)
        self.labelH_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_6.setObjectName("labelH_6")
        self.gridLayout_6.addWidget(self.labelH_6, 0, 4, 1, 1)
        self.copterH_6 = QtGui.QLabel(self.layoutWidget_12)
        self.copterH_6.setAlignment(QtCore.Qt.AlignCenter)
        self.copterH_6.setObjectName("copterH_6")
        self.gridLayout_6.addWidget(self.copterH_6, 1, 4, 1, 1)
        self.offsetH_6 = QtGui.QDoubleSpinBox(self.layoutWidget_12)
        self.offsetH_6.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetH_6.setDecimals(0)
        self.offsetH_6.setMinimum(-359.0)
        self.offsetH_6.setMaximum(359.0)
        self.offsetH_6.setSingleStep(1.0)
        self.offsetH_6.setObjectName("offsetH_6")
        self.gridLayout_6.addWidget(self.offsetH_6, 2, 4, 1, 1)
        self.layoutWidget_13 = QtGui.QWidget(self.groupCopter_6)
        self.layoutWidget_13.setGeometry(QtCore.QRect(60, 30, 51, 53))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.copterVolts_6 = QtGui.QLabel(self.layoutWidget_13)
        self.copterVolts_6.setObjectName("copterVolts_6")
        self.verticalLayout_8.addWidget(self.copterVolts_6)
        self.copterAmps_6 = QtGui.QLabel(self.layoutWidget_13)
        self.copterAmps_6.setObjectName("copterAmps_6")
        self.verticalLayout_8.addWidget(self.copterAmps_6)
        self.copterMode_6 = QtGui.QLabel(self.layoutWidget_13)
        self.copterMode_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copterMode_6.setObjectName("copterMode_6")
        self.verticalLayout_8.addWidget(self.copterMode_6)
        self.copterColor6 = QtGui.QPushButton(self.groupCopter_6)
        self.copterColor6.setGeometry(QtCore.QRect(10, 10, 41, 71))
        self.copterColor6.setCursor(QtCore.Qt.PointingHandCursor)
        self.copterColor6.setStyleSheet("font: bold italic 30pt \"Verdana\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.copterColor6.setObjectName("copterColor6")
        self.groupCopter_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupCopter_5.setGeometry(QtCore.QRect(1410, 410, 331, 91))
        self.groupCopter_5.setTitle("")
        self.groupCopter_5.setObjectName("groupCopter_5")
        self.copterBatteryIndicator_5 = QtGui.QProgressBar(self.groupCopter_5)
        self.copterBatteryIndicator_5.setGeometry(QtCore.QRect(60, 10, 261, 16))
        self.copterBatteryIndicator_5.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.copterBatteryIndicator_5.setMinimum(130)
        self.copterBatteryIndicator_5.setMaximum(168)
        self.copterBatteryIndicator_5.setProperty("value", 129)
        self.copterBatteryIndicator_5.setTextVisible(False)
        self.copterBatteryIndicator_5.setOrientation(QtCore.Qt.Horizontal)
        self.copterBatteryIndicator_5.setObjectName("copterBatteryIndicator_5")
        self.layoutWidget_10 = QtGui.QWidget(self.groupCopter_5)
        self.layoutWidget_10.setGeometry(QtCore.QRect(110, 30, 211, 54))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_10)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(1)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.offsetY_5 = QtGui.QDoubleSpinBox(self.layoutWidget_10)
        self.offsetY_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetY_5.setMinimum(-1.0)
        self.offsetY_5.setMaximum(1.0)
        self.offsetY_5.setSingleStep(0.01)
        self.offsetY_5.setObjectName("offsetY_5")
        self.gridLayout_5.addWidget(self.offsetY_5, 2, 1, 1, 1)
        self.offsetX_5 = QtGui.QDoubleSpinBox(self.layoutWidget_10)
        self.offsetX_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetX_5.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.offsetX_5.setMinimum(-1.0)
        self.offsetX_5.setMaximum(1.0)
        self.offsetX_5.setSingleStep(0.01)
        self.offsetX_5.setObjectName("offsetX_5")
        self.gridLayout_5.addWidget(self.offsetX_5, 2, 0, 1, 1)
        self.copterX_5 = QtGui.QLabel(self.layoutWidget_10)
        self.copterX_5.setAlignment(QtCore.Qt.AlignCenter)
        self.copterX_5.setObjectName("copterX_5")
        self.gridLayout_5.addWidget(self.copterX_5, 1, 0, 1, 1)
        self.copterY_5 = QtGui.QLabel(self.layoutWidget_10)
        self.copterY_5.setAlignment(QtCore.Qt.AlignCenter)
        self.copterY_5.setObjectName("copterY_5")
        self.gridLayout_5.addWidget(self.copterY_5, 1, 1, 1, 1)
        self.offsetZ_5 = QtGui.QDoubleSpinBox(self.layoutWidget_10)
        self.offsetZ_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetZ_5.setMinimum(-1.0)
        self.offsetZ_5.setMaximum(1.0)
        self.offsetZ_5.setSingleStep(0.01)
        self.offsetZ_5.setObjectName("offsetZ_5")
        self.gridLayout_5.addWidget(self.offsetZ_5, 2, 3, 1, 1)
        self.labelX_5 = QtGui.QLabel(self.layoutWidget_10)
        self.labelX_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_5.setObjectName("labelX_5")
        self.gridLayout_5.addWidget(self.labelX_5, 0, 0, 1, 1)
        self.copterZ_5 = QtGui.QLabel(self.layoutWidget_10)
        self.copterZ_5.setAlignment(QtCore.Qt.AlignCenter)
        self.copterZ_5.setObjectName("copterZ_5")
        self.gridLayout_5.addWidget(self.copterZ_5, 1, 3, 1, 1)
        self.labelY_5 = QtGui.QLabel(self.layoutWidget_10)
        self.labelY_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_5.setObjectName("labelY_5")
        self.gridLayout_5.addWidget(self.labelY_5, 0, 1, 1, 1)
        self.labelZ_5 = QtGui.QLabel(self.layoutWidget_10)
        self.labelZ_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_5.setObjectName("labelZ_5")
        self.gridLayout_5.addWidget(self.labelZ_5, 0, 3, 1, 1)
        self.labelH_5 = QtGui.QLabel(self.layoutWidget_10)
        self.labelH_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_5.setObjectName("labelH_5")
        self.gridLayout_5.addWidget(self.labelH_5, 0, 4, 1, 1)
        self.copterH_5 = QtGui.QLabel(self.layoutWidget_10)
        self.copterH_5.setAlignment(QtCore.Qt.AlignCenter)
        self.copterH_5.setObjectName("copterH_5")
        self.gridLayout_5.addWidget(self.copterH_5, 1, 4, 1, 1)
        self.offsetH_5 = QtGui.QDoubleSpinBox(self.layoutWidget_10)
        self.offsetH_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetH_5.setDecimals(0)
        self.offsetH_5.setMinimum(-359.0)
        self.offsetH_5.setMaximum(359.0)
        self.offsetH_5.setSingleStep(1.0)
        self.offsetH_5.setObjectName("offsetH_5")
        self.gridLayout_5.addWidget(self.offsetH_5, 2, 4, 1, 1)
        self.layoutWidget_11 = QtGui.QWidget(self.groupCopter_5)
        self.layoutWidget_11.setGeometry(QtCore.QRect(60, 30, 51, 53))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.copterVolts_5 = QtGui.QLabel(self.layoutWidget_11)
        self.copterVolts_5.setObjectName("copterVolts_5")
        self.verticalLayout_7.addWidget(self.copterVolts_5)
        self.copterAmps_5 = QtGui.QLabel(self.layoutWidget_11)
        self.copterAmps_5.setObjectName("copterAmps_5")
        self.verticalLayout_7.addWidget(self.copterAmps_5)
        self.copterMode_5 = QtGui.QLabel(self.layoutWidget_11)
        self.copterMode_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copterMode_5.setObjectName("copterMode_5")
        self.verticalLayout_7.addWidget(self.copterMode_5)
        self.copterColor5 = QtGui.QPushButton(self.groupCopter_5)
        self.copterColor5.setGeometry(QtCore.QRect(10, 10, 41, 71))
        self.copterColor5.setCursor(QtCore.Qt.PointingHandCursor)
        self.copterColor5.setStyleSheet("font: bold italic 30pt \"Verdana\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.copterColor5.setObjectName("copterColor5")
        self.groupCopter_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupCopter_3.setGeometry(QtCore.QRect(1410, 210, 331, 91))
        self.groupCopter_3.setTitle("")
        self.groupCopter_3.setObjectName("groupCopter_3")
        self.copterBatteryIndicator_3 = QtGui.QProgressBar(self.groupCopter_3)
        self.copterBatteryIndicator_3.setGeometry(QtCore.QRect(60, 10, 261, 16))
        self.copterBatteryIndicator_3.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(170, 85, 255);")
        self.copterBatteryIndicator_3.setMinimum(130)
        self.copterBatteryIndicator_3.setMaximum(168)
        self.copterBatteryIndicator_3.setProperty("value", 129)
        self.copterBatteryIndicator_3.setTextVisible(False)
        self.copterBatteryIndicator_3.setOrientation(QtCore.Qt.Horizontal)
        self.copterBatteryIndicator_3.setObjectName("copterBatteryIndicator_3")
        self.layoutWidget_6 = QtGui.QWidget(self.groupCopter_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(110, 30, 211, 54))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.offsetY_3 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.offsetY_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetY_3.setMinimum(-1.0)
        self.offsetY_3.setMaximum(1.0)
        self.offsetY_3.setSingleStep(0.01)
        self.offsetY_3.setObjectName("offsetY_3")
        self.gridLayout_3.addWidget(self.offsetY_3, 2, 1, 1, 1)
        self.offsetX_3 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.offsetX_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetX_3.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.offsetX_3.setMinimum(-1.0)
        self.offsetX_3.setMaximum(1.0)
        self.offsetX_3.setSingleStep(0.01)
        self.offsetX_3.setObjectName("offsetX_3")
        self.gridLayout_3.addWidget(self.offsetX_3, 2, 0, 1, 1)
        self.copterX_3 = QtGui.QLabel(self.layoutWidget_6)
        self.copterX_3.setAlignment(QtCore.Qt.AlignCenter)
        self.copterX_3.setObjectName("copterX_3")
        self.gridLayout_3.addWidget(self.copterX_3, 1, 0, 1, 1)
        self.copterY_3 = QtGui.QLabel(self.layoutWidget_6)
        self.copterY_3.setAlignment(QtCore.Qt.AlignCenter)
        self.copterY_3.setObjectName("copterY_3")
        self.gridLayout_3.addWidget(self.copterY_3, 1, 1, 1, 1)
        self.offsetZ_3 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.offsetZ_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetZ_3.setMinimum(-1.0)
        self.offsetZ_3.setMaximum(1.0)
        self.offsetZ_3.setSingleStep(0.01)
        self.offsetZ_3.setObjectName("offsetZ_3")
        self.gridLayout_3.addWidget(self.offsetZ_3, 2, 3, 1, 1)
        self.labelX_3 = QtGui.QLabel(self.layoutWidget_6)
        self.labelX_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX_3.setObjectName("labelX_3")
        self.gridLayout_3.addWidget(self.labelX_3, 0, 0, 1, 1)
        self.copterZ_3 = QtGui.QLabel(self.layoutWidget_6)
        self.copterZ_3.setAlignment(QtCore.Qt.AlignCenter)
        self.copterZ_3.setObjectName("copterZ_3")
        self.gridLayout_3.addWidget(self.copterZ_3, 1, 3, 1, 1)
        self.labelY_3 = QtGui.QLabel(self.layoutWidget_6)
        self.labelY_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY_3.setObjectName("labelY_3")
        self.gridLayout_3.addWidget(self.labelY_3, 0, 1, 1, 1)
        self.labelZ_3 = QtGui.QLabel(self.layoutWidget_6)
        self.labelZ_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ_3.setObjectName("labelZ_3")
        self.gridLayout_3.addWidget(self.labelZ_3, 0, 3, 1, 1)
        self.labelH_3 = QtGui.QLabel(self.layoutWidget_6)
        self.labelH_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH_3.setObjectName("labelH_3")
        self.gridLayout_3.addWidget(self.labelH_3, 0, 4, 1, 1)
        self.copterH_3 = QtGui.QLabel(self.layoutWidget_6)
        self.copterH_3.setAlignment(QtCore.Qt.AlignCenter)
        self.copterH_3.setObjectName("copterH_3")
        self.gridLayout_3.addWidget(self.copterH_3, 1, 4, 1, 1)
        self.offsetH_3 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.offsetH_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.offsetH_3.setDecimals(0)
        self.offsetH_3.setMinimum(-359.0)
        self.offsetH_3.setMaximum(359.0)
        self.offsetH_3.setSingleStep(1.0)
        self.offsetH_3.setObjectName("offsetH_3")
        self.gridLayout_3.addWidget(self.offsetH_3, 2, 4, 1, 1)
        self.layoutWidget_7 = QtGui.QWidget(self.groupCopter_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(60, 30, 51, 53))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.copterVolts_3 = QtGui.QLabel(self.layoutWidget_7)
        self.copterVolts_3.setObjectName("copterVolts_3")
        self.verticalLayout_5.addWidget(self.copterVolts_3)
        self.copterAmps_3 = QtGui.QLabel(self.layoutWidget_7)
        self.copterAmps_3.setObjectName("copterAmps_3")
        self.verticalLayout_5.addWidget(self.copterAmps_3)
        self.copterMode_3 = QtGui.QLabel(self.layoutWidget_7)
        self.copterMode_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copterMode_3.setObjectName("copterMode_3")
        self.verticalLayout_5.addWidget(self.copterMode_3)
        self.copterColor3 = QtGui.QPushButton(self.groupCopter_3)
        self.copterColor3.setGeometry(QtCore.QRect(10, 10, 41, 71))
        self.copterColor3.setCursor(QtCore.Qt.PointingHandCursor)
        self.copterColor3.setStyleSheet("font: bold italic 30pt \"Verdana\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.copterColor3.setObjectName("copterColor3")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 611))
        self.groupBox.setObjectName("groupBox")
        self.Instructions = QtGui.QLabel(self.groupBox)
        self.Instructions.setGeometry(QtCore.QRect(10, 20, 211, 461))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.Instructions.setFont(font)
        self.Instructions.setScaledContents(False)
        self.Instructions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Instructions.setWordWrap(True)
        self.Instructions.setObjectName("Instructions")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Soar1NG Intern Ground Station", None, QtGui.QApplication.UnicodeUTF8))
        self.groupMarkedLocations.setTitle(QtGui.QApplication.translate("MainWindow", "Marked Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnADDWP.setText(QtGui.QApplication.translate("MainWindow", "ADD", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnREMOVEWP.setText(QtGui.QApplication.translate("MainWindow", "REMOVE", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnGOTO.setText(QtGui.QApplication.translate("MainWindow", "GO TO", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_L.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_L.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_L.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_L.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.markedLocationsList.isSortingEnabled()
        self.markedLocationsList.setSortingEnabled(False)
        self.markedLocationsList.item(0).setText(QtGui.QApplication.translate("MainWindow", "Attack 1", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(1).setText(QtGui.QApplication.translate("MainWindow", "Attack 2", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(2).setText(QtGui.QApplication.translate("MainWindow", "Attack 3", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(3).setText(QtGui.QApplication.translate("MainWindow", "Ball Drop 1", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(4).setText(QtGui.QApplication.translate("MainWindow", "Ball Drop 2", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(5).setText(QtGui.QApplication.translate("MainWindow", "Ball Drop 3", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(6).setText(QtGui.QApplication.translate("MainWindow", "Defend 1", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(7).setText(QtGui.QApplication.translate("MainWindow", "Defend 2", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.item(8).setText(QtGui.QApplication.translate("MainWindow", "Defend 3", None, QtGui.QApplication.UnicodeUTF8))
        self.markedLocationsList.setSortingEnabled(__sortingEnabled)
        self.pbtnETCWP.setText(QtGui.QApplication.translate("MainWindow", "ETC", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnDROPWP.setText(QtGui.QApplication.translate("MainWindow", "DROP", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnSHOOTWP.setText(QtGui.QApplication.translate("MainWindow", "SHOOT", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnBLOCKWP.setText(QtGui.QApplication.translate("MainWindow", "BLOCK", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnALLWP.setText(QtGui.QApplication.translate("MainWindow", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.groupCopterActions.setTitle(QtGui.QApplication.translate("MainWindow", "Copter Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnARM.setText(QtGui.QApplication.translate("MainWindow", "ARM/TAKEOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnLAND.setText(QtGui.QApplication.translate("MainWindow", "LAND", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnDISCONNECT.setText(QtGui.QApplication.translate("MainWindow", "DISCONNECT", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnKILL.setText(QtGui.QApplication.translate("MainWindow", "KILL", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMaxSpeed.setText(QtGui.QApplication.translate("MainWindow", "Max Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMaxSpeed_2.setText(QtGui.QApplication.translate("MainWindow", "m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIncrementSpeed.setText(QtGui.QApplication.translate("MainWindow", "Increment Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIncrementSpeedVALUE.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnFLIP.setText(QtGui.QApplication.translate("MainWindow", "(╯°□°）╯︵ ┻┻ ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnLOB.setText(QtGui.QApplication.translate("MainWindow", "(╯°□°）╯︵︵︵┻┻ ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnFOLLOW.setText(QtGui.QApplication.translate("MainWindow", "FOLLOW", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnPLATOON.setText(QtGui.QApplication.translate("MainWindow", "PLATOON", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnPATROL.setText(QtGui.QApplication.translate("MainWindow", "PATROL", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnWALL.setText(QtGui.QApplication.translate("MainWindow", "WALL", None, QtGui.QApplication.UnicodeUTF8))
        self.copterBatteryIndicator_1.setFormat(QtGui.QApplication.translate("MainWindow", "%v V", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_1.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.copterZ_1.setText(QtGui.QApplication.translate("MainWindow", "Z-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_1.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.copterX_1.setText(QtGui.QApplication.translate("MainWindow", "X-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_1.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.copterY_1.setText(QtGui.QApplication.translate("MainWindow", "Y-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_1.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.copterH_1.setText(QtGui.QApplication.translate("MainWindow", "H_BRNG", None, QtGui.QApplication.UnicodeUTF8))
        self.copterVolts_1.setText(QtGui.QApplication.translate("MainWindow", "VOLTs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterAmps_1.setText(QtGui.QApplication.translate("MainWindow", "AMPs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterMode_1.setText(QtGui.QApplication.translate("MainWindow", "MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.copterColor1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.copterBatteryIndicator_2.setFormat(QtGui.QApplication.translate("MainWindow", "%v V", None, QtGui.QApplication.UnicodeUTF8))
        self.copterY_2.setText(QtGui.QApplication.translate("MainWindow", "Y-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.copterX_2.setText(QtGui.QApplication.translate("MainWindow", "X-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.copterZ_2.setText(QtGui.QApplication.translate("MainWindow", "Z-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_2.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_2.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_2.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.copterH_2.setText(QtGui.QApplication.translate("MainWindow", "H_BRNG", None, QtGui.QApplication.UnicodeUTF8))
        self.copterVolts_2.setText(QtGui.QApplication.translate("MainWindow", "VOLTs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterAmps_2.setText(QtGui.QApplication.translate("MainWindow", "AMPs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterMode_2.setText(QtGui.QApplication.translate("MainWindow", "MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.copterColor2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.copterBatteryIndicator_4.setFormat(QtGui.QApplication.translate("MainWindow", "%v V", None, QtGui.QApplication.UnicodeUTF8))
        self.copterX_4.setText(QtGui.QApplication.translate("MainWindow", "X-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.copterY_4.setText(QtGui.QApplication.translate("MainWindow", "Y-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_4.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.copterZ_4.setText(QtGui.QApplication.translate("MainWindow", "Z-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_4.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_4.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_4.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.copterH_4.setText(QtGui.QApplication.translate("MainWindow", "H_BRNG", None, QtGui.QApplication.UnicodeUTF8))
        self.copterVolts_4.setText(QtGui.QApplication.translate("MainWindow", "VOLTs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterAmps_4.setText(QtGui.QApplication.translate("MainWindow", "AMPs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterMode_4.setText(QtGui.QApplication.translate("MainWindow", "MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.copterColor4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.copterBatteryIndicator_6.setFormat(QtGui.QApplication.translate("MainWindow", "%v V", None, QtGui.QApplication.UnicodeUTF8))
        self.copterX_6.setText(QtGui.QApplication.translate("MainWindow", "X-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.copterY_6.setText(QtGui.QApplication.translate("MainWindow", "Y-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_6.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.copterZ_6.setText(QtGui.QApplication.translate("MainWindow", "Z-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_6.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_6.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_6.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.copterH_6.setText(QtGui.QApplication.translate("MainWindow", "H_BRNG", None, QtGui.QApplication.UnicodeUTF8))
        self.copterVolts_6.setText(QtGui.QApplication.translate("MainWindow", "VOLTs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterAmps_6.setText(QtGui.QApplication.translate("MainWindow", "AMPs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterMode_6.setText(QtGui.QApplication.translate("MainWindow", "MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.copterColor6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.copterBatteryIndicator_5.setFormat(QtGui.QApplication.translate("MainWindow", "%v V", None, QtGui.QApplication.UnicodeUTF8))
        self.copterX_5.setText(QtGui.QApplication.translate("MainWindow", "X-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.copterY_5.setText(QtGui.QApplication.translate("MainWindow", "Y-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_5.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.copterZ_5.setText(QtGui.QApplication.translate("MainWindow", "Z-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_5.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_5.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_5.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.copterH_5.setText(QtGui.QApplication.translate("MainWindow", "H_BRNG", None, QtGui.QApplication.UnicodeUTF8))
        self.copterVolts_5.setText(QtGui.QApplication.translate("MainWindow", "VOLTs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterAmps_5.setText(QtGui.QApplication.translate("MainWindow", "AMPs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterMode_5.setText(QtGui.QApplication.translate("MainWindow", "MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.copterColor5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.copterBatteryIndicator_3.setFormat(QtGui.QApplication.translate("MainWindow", "%v V", None, QtGui.QApplication.UnicodeUTF8))
        self.copterX_3.setText(QtGui.QApplication.translate("MainWindow", "X-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.copterY_3.setText(QtGui.QApplication.translate("MainWindow", "Y-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX_3.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.copterZ_3.setText(QtGui.QApplication.translate("MainWindow", "Z-LOC", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY_3.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelZ_3.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelH_3.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.copterH_3.setText(QtGui.QApplication.translate("MainWindow", "H_BRNG", None, QtGui.QApplication.UnicodeUTF8))
        self.copterVolts_3.setText(QtGui.QApplication.translate("MainWindow", "VOLTs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterAmps_3.setText(QtGui.QApplication.translate("MainWindow", "AMPs", None, QtGui.QApplication.UnicodeUTF8))
        self.copterMode_3.setText(QtGui.QApplication.translate("MainWindow", "MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.copterColor3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.Instructions.setText(QtGui.QApplication.translate("MainWindow", "Keybinds go here.", None, QtGui.QApplication.UnicodeUTF8))

